name: SFML_CI_TEST

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: setup environment
      run: |
        sudo apt-get install valgrind libpthread-stubs0-dev libx11-dev libxrandr-dev libfreetype6-dev libglew1.5-dev libjpeg8-dev libsndfile1-dev libopenal-dev libudev-dev xvfb
        sudo ldconfig -p | grep -i gl.so
        sudo mv /usr/lib/x86_64-linux-gnu/libGL.so.1 /usr/lib/x86_64-linux-gnu/libGL.so.1.ORIGINAL
        sudo mv /usr/lib/x86_64-linux-gnu/libGL.so.1.ORIGINAL /usr/lib/x86_64-linux-gnu/libGL.so.1
        sudo mv /usr/lib/x86_64-linux-gnu/libGL.so /usr/lib/x86_64-linux-gnu/libGL.so.ORIGINAL
        sudo mv /usr/lib/x86_64-linux-gnu/libGL.so.ORIGINAL /usr/lib/x86_64-linux-gnu/libGL.so

    - name: Build
      run: |
        mkdir Build_Dir
        cd Build_Dir/
        cmake ../ -DBUILD_SHARED_LIBS=OFF
        make

    - name: setup Xvfb
      run: |
        Xvfb :99 &

    - name: Test
      run: |
        cd Build_Dir
        ./sfml_actions_test
      env:
        DISPLAY: :99

    - name: Valgrind
      run: |
        cd Build_Dir
        valgrind ./sfml_actions_test
      env:
        DISPLAY: :99
