name: SFML_CI_TEST

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: setup environment
      run: |
        sudo apt-get install valgrind libpthread-stubs0-dev libx11-dev libxrandr-dev libfreetype6-dev libglew1.5-dev libjpeg8-dev libsndfile1-dev libopenal-dev libudev-dev xvfb tree
    - name: Build
      run: |
        mkdir Build_Dir
        cd Build_Dir/
        cmake ../ -DBUILD_SHARED_LIBS=OFF
        make

    - name: setup Xvfb
      run: |
        Xvfb :99 &

    - name: Test
      run: |
        pwd && tree .
        cd build/bin
        ./sfml_actions_test
      env:
        DISPLAY: :99
